{
 "title": "PBSpro_License_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "LMX License Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "GlobalZoneAP_license_avail", "legendFormat": "Free" },
    {
     "expr": "GlobalZoneAP_license_total - GlobalZoneAP_license_avail",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ANSYS License Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ansys_license_avail", "legendFormat": "Free" },
    {
     "expr": "ansys_license_total - ansys_license_avail",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ANSHPC_PACK License Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "anshpc_pack_license_avail", "legendFormat": "Free" },
    {
     "expr": "anshpc_pack_license_total - anshpc_pack_license_avail",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CFD_BASE License Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cfd_base_license_avail", "legendFormat": "Free" },
    {
     "expr": "cfd_base_license_total - cfd_base_license_avail",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ELEC_SOLVE_HFSS License Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "elec_solve_hfss_license_avail", "legendFormat": "Free" },
    {
     "expr": "elec_solve_hfss_license_total - elec_solve_hfss_license_avail",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ELEC_SOLVE_LEVEL1 License Usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "elec_solve_level1_license_avail",
     "legendFormat": "Free"
    },
    {
     "expr": "elec_solve_level1_license_total - elec_solve_level1_license_avail",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}