{
 "title": "PBSpro_Queue_Dashboard",
 "description": "PBSpro Queue State Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "QueueName", "query": "label_values(QueueName)" },
   { "name": "QueueType", "query": "label_values(QueueType)" }
  ]
 },
 "panels": [
  {
   "title": "Queue State",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "pbspro_qstat_queue_enable{}", "legendFormat": "{{QueueName}}" }
   ]
  },
  {
   "title": "Jobs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(pbspro_qstat_jobs_etime) by (VariableListQueue)",
     "legendFormat": "{{lVariableListQueue}}"
    }
   ]
  },
  {
   "title": "Running CPUs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(VariableListQueue)(pbspro_qstat_jobs_resources_list_ncpus{JobState=\"R\"})",
     "legendFormat": "{{VariableListQueue}}"
    }
   ]
  },
  {
   "title": "Queued CPUs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(VariableListQueue)(pbspro_qstat_jobs_resources_list_ncpus{JobState=\"Q\"})",
     "legendFormat": "{{VariableListQueue}}"
    }
   ]
  },
  {
   "title": "Job count [azcloudq]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"azcloudq\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"azcloudq\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"azcloudq\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"azcloudq\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"azcloudq\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"azcloudq\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [iworkq]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"iworkq\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"iworkq\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"iworkq\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"iworkq\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"iworkq\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"iworkq\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [workq]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"workq\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"workq\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"workq\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"workq\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"workq\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"workq\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [dummy]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"dummy\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"dummy\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"dummy\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"dummy\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"dummy\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"dummy\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [lsdyna]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"lsdyna\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"lsdyna\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"lsdyna\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"lsdyna\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"lsdyna\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"lsdyna\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [dm]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"dm\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"dm\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"dm\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"dm\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"dm\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"dm\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [oci]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"oci\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"oci\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"oci\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"oci\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"oci\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"oci\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [sdcaws]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"sdcaws\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"sdcaws\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"sdcaws\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"sdcaws\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"sdcaws\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"sdcaws\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [awsback]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"awsback\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"awsback\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"awsback\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"awsback\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"awsback\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"awsback\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [gcp]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"gcp\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"gcp\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"gcp\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"gcp\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"gcp\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"gcp\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [azureA]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"azureA\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"azureA\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"azureA\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"azureA\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"azureA\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"azureA\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [gpu2]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"gpu2\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"gpu2\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"gpu2\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"gpu2\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"gpu2\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"gpu2\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [local]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"local\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"local\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"local\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"local\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"local\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"local\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [gpu]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"gpu\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"gpu\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"gpu\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"gpu\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"gpu\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"gpu\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [ls]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"ls\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"ls\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"ls\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"ls\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"ls\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"ls\"}",
     "legendFormat": "Transit"
    }
   ]
  },
  {
   "title": "Job count [sdclocal]",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_begun_state_count{QueueName=\"sdclocal\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_queue_exiting_state_count{QueueName=\"sdclocal\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_queue_held_state_count{QueueName=\"sdclocal\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_queue_queued_state_count{QueueName=\"sdclocal\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_queue_running_state_count{QueueName=\"sdclocal\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_queue_transit_state_count{QueueName=\"sdclocal\"}",
     "legendFormat": "Transit"
    }
   ]
  }
 ]
}