{
 "title": "PBSpro_Server_Dashboard",
 "description": "PBSpro Server State Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "QueueName", "query": "label_values(QueueName)" },
   { "name": "ServerName", "query": "label_values(ServerName)" },
   { "name": "Version", "query": "label_values(PBSVersion)" },
   { "name": "ServerState", "query": "label_values(PBSVersion)" }
  ]
 },
 "panels": [
  {
   "title": "ServerTotalJobs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_server_total_jobs{ServerName=\"$ServerName\"}",
     "legendFormat": "TotalJobs"
    }
   ]
  },
  {
   "title": "LicenseLifetime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_server_flicenses{ServerName=\"$ServerName\"}",
     "legendFormat": "FLicenses"
    }
   ]
  },
  {
   "title": "ServerLogEvents",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_server_log_events{ServerName=\"$ServerName\"}",
     "legendFormat": "Events"
    }
   ]
  },
  {
   "title": "Scheduling",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_server_scheduling{ServerName=\"$ServerName\"}",
     "legendFormat": "Scheduling"
    }
   ]
  },
  {
   "title": "DefaultChunkNcpus",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_server_default_chunk_ncpus{ServerName=\"$ServerName\"}",
     "legendFormat": "DefaultChunkNcpus"
    }
   ]
  },
  {
   "title": "ServerState",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "pbspro_qstat_server_state{ServerName=\"$ServerName\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "State",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "ServerEnableHistory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_server_job_history_enable{ServerName=\"$ServerName\"}",
     "legendFormat": "EnableHistory"
    }
   ]
  },
  {
   "title": "ServerHistoryDuration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_server_job_history_duration{ServerName=\"$ServerName\"}",
     "legendFormat": "HistoryDuration"
    }
   ]
  },
  {
   "title": "StateCountPercent",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pbspro_qstat_server_begun_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "Begun"
    },
    {
     "expr": "pbspro_qstat_server_transit_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "Transit"
    },
    {
     "expr": "pbspro_qstat_server_held_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "Held"
    },
    {
     "expr": "pbspro_qstat_server_waiting_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "pbspro_qstat_server_exiting_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "Exiting"
    },
    {
     "expr": "pbspro_qstat_server_queued_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_server_running_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "ServerStateCount",
   "type": "timeseries",
   "description": "pbspro_qstat_server_running_state_count",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pbspro_qstat_server_running_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "RunningState"
    },
    {
     "expr": "pbspro_qstat_server_transit_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "TransitState"
    },
    {
     "expr": "pbspro_qstat_server_queued_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "QueuedState"
    },
    {
     "expr": "pbspro_qstat_server_waiting_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "WaitingState"
    },
    {
     "expr": "pbspro_qstat_server_held_state_count{ServerName=\"$ServerName\"}",
     "legendFormat": "HeldState"
    }
   ]
  },
  {
   "title": "LicenseCount",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "pbspro_qstat_server_license_count_avail_global{ServerName=\"$ServerName\"}",
     "legendFormat": "AvailGlobal"
    },
    {
     "expr": "pbspro_qstat_server_license_count_avail_local{ServerName=\"$ServerName\"}",
     "legendFormat": "AvailLocal"
    },
    {
     "expr": "pbspro_qstat_server_license_count_high_use{ServerName=\"$ServerName\"}",
     "legendFormat": "HighUsed"
    },
    {
     "expr": "pbspro_qstat_server_license_count_used{ServerName=\"$ServerName\"}",
     "legendFormat": "Used"
    }
   ]
  }
 ]
}