{
 "title": "PBSpro_Jobs_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Job State",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (JobState) (pbspro_qstat_jobs_etime)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs by User",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by(JobOwner) (pbspro_qstat_jobs_etime)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running CPUs by User",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(JobOwner)(pbspro_qstat_jobs_resources_list_ncpus{JobState=\"R\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued CPUs by User",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(JobOwner)(pbspro_qstat_jobs_resources_list_ncpus{JobState=\"Q\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPUs by State",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (JobState) (pbspro_qstat_jobs_resources_list_ncpus)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jobs by State",
   "type": "timeseries",
   "description": "pbspro_qstat_server_running_state_count",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pbspro_qstat_server_running_state_count{ServerName=\"pbsm\"}",
     "legendFormat": "Running"
    },
    {
     "expr": "pbspro_qstat_server_transit_state_count{ServerName=\"pbsm\"}",
     "legendFormat": "Transit"
    },
    {
     "expr": "pbspro_qstat_server_queued_state_count{ServerName=\"pbsm\"}",
     "legendFormat": "Queued"
    },
    {
     "expr": "pbspro_qstat_server_waiting_state_count{ServerName=\"pbsm\"}",
     "legendFormat": "Waiting"
    },
    {
     "expr": "pbspro_qstat_server_held_state_count{ServerName=\"pbsm\"}",
     "legendFormat": "Held"
    }
   ]
  },
  {
   "title": "Total Jobs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "pbspro_qstat_queue_total_jobs", "legendFormat": "{{QueueName}}" }
   ]
  },
  {
   "title": "Queued Jobs by Queue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "pbspro_qstat_queue_queued_state_count",
     "legendFormat": "{{QueueName}}"
    }
   ]
  }
 ]
}