{
 "title": "PBSpro_Node_Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Available CPUs by Node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (NodeName) (pbspro_qstat_node_resources_available_ncpus - pbspro_qstat_node_resources_assigned_ncpus)",
     "legendFormat": "{{NodeName}}"
    },
    {
     "expr": "sum by (NodeName) (pbspro_qstat_node_resources_available_ncpus)",
     "legendFormat": "{{NodeName}}"
    }
   ]
  },
  {
   "title": "Node status",
   "type": "status-history",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by(NodeName) (pbspro_qstat_node_state)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Assigned CPUs by Node",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum by (NodeName) (pbspro_qstat_node_resources_assigned_ncpus)",
     "legendFormat": "{{NodeName}}"
    }
   ]
  }
 ]
}